-- spendings-list: пълна схема за Supabase (Postgres), крайно състояние.
--
-- ЗА ПРАЗЕН проект (Supabase -> SQL Editor -> New query -> Run).
-- НЕ го пускай върху съществуващата база: таблиците вече са там.
--
-- Преди да го пуснеш, в Authentication настрой:
--   - Sign In / Providers: изключи "Allow new users to sign up"
--   - Email: изключи "Confirm email"
-- След като го пуснеш: създай потребителите (Authentication -> Users -> Add user,
-- имейл <име>@spendings.app, парола = 6-цифрен PIN, "Auto Confirm User"),
-- после направи админ:
--   update public.profiles set is_admin = true where name = '<име>';

-- ============ ТАБЛИЦИ ============

-- Профил към всеки Supabase Auth потребител.
-- name = логин името (латиница, малки букви) = частта пред @ в имейла.
create table public.profiles (
  id         uuid primary key references auth.users(id) on delete cascade,
  name       text not null unique,
  is_admin   boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.categories (
  id         bigint generated by default as identity primary key,
  name       text not null unique,
  active     boolean not null default true,   -- скриване без триене
  sort_order int not null default 0,          -- ред в менюто
  created_at timestamptz not null default now()
);

create table public.expenses (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null default auth.uid()
              references public.profiles(id) on delete cascade,
  category_id bigint not null
              references public.categories(id) on update cascade on delete restrict,
  amount      numeric(10,2) not null,
  spent_on    date not null default current_date,
  description text not null default '',
  deleted_at  timestamptz,                    -- не null = в кошчето
  client_id   uuid not null default gen_random_uuid() unique,  -- защита от дубли
  created_at  timestamptz not null default now()
);

create index expenses_user_date_idx on public.expenses (user_id, spent_on desc);
create index expenses_date_idx      on public.expenses (spent_on);
create index expenses_category_idx  on public.expenses (category_id);
create index expenses_live_idx      on public.expenses (spent_on) where deleted_at is null;

-- Лични шаблони за повтарящи се разходи.
create table public.templates (
  id          bigint generated by default as identity primary key,
  user_id     uuid not null default auth.uid()
              references public.profiles(id) on delete cascade,
  title       text not null,
  category_id bigint not null
              references public.categories(id) on update cascade on delete restrict,
  amount      numeric(10,2),                  -- може да е празна
  sort_order  int not null default 0,
  created_at  timestamptz not null default now()
);

create index templates_user_idx on public.templates (user_id, sort_order);

-- ============ ФУНКЦИИ ============

-- Автоматичен профил при нов Auth потребител.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1))
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Помощна функция за RLS политиките.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select is_admin from public.profiles where id = auth.uid()), false);
$$;

-- Изтриване в кошчето: собственик или админ.
create or replace function public.delete_expense(p_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  update public.expenses
     set deleted_at = now()
   where id = p_id
     and deleted_at is null
     and (user_id = auth.uid() or public.is_admin());
  if not found then
    raise exception 'Expense not found or not allowed';
  end if;
end;
$$;

-- ============ ROW LEVEL SECURITY ============

alter table public.profiles   enable row level security;
alter table public.categories enable row level security;
alter table public.expenses   enable row level security;
alter table public.templates  enable row level security;

-- profiles: всеки вижда своя, админът всички; променя само админът
create policy "profiles: read own or admin"
  on public.profiles for select to authenticated
  using (id = auth.uid() or public.is_admin());

create policy "profiles: admin updates"
  on public.profiles for update to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- categories: всички влезли ги четат, променя само админът
create policy "categories: read"
  on public.categories for select to authenticated
  using (true);

create policy "categories: admin insert"
  on public.categories for insert to authenticated
  with check (public.is_admin());

create policy "categories: admin update"
  on public.categories for update to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "categories: admin delete"
  on public.categories for delete to authenticated
  using (public.is_admin());

-- expenses: член вижда само своите неизтрити; админът вижда всичко (и кошчето)
create policy "expenses: read"
  on public.expenses for select to authenticated
  using (public.is_admin() or (user_id = auth.uid() and deleted_at is null));

create policy "expenses: insert own"
  on public.expenses for insert to authenticated
  with check (user_id = auth.uid() and deleted_at is null);

-- член редактира своите неизтрити, но не може да пипа deleted_at
create policy "expenses: update own"
  on public.expenses for update to authenticated
  using      (user_id = auth.uid() and deleted_at is null)
  with check (user_id = auth.uid() and deleted_at is null);

-- админът редактира всичко и връща от кошчето (deleted_at = null)
create policy "expenses: admin update"
  on public.expenses for update to authenticated
  using (public.is_admin()) with check (public.is_admin());

-- окончателно триене - само админ
create policy "expenses: admin delete"
  on public.expenses for delete to authenticated
  using (public.is_admin());

-- templates: само собственикът
create policy "templates: own"
  on public.templates for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

-- ============ СПРАВКИ ============

-- Суми по потребител x категория x месец (само неизтрити).
-- security_invoker = RLS важи: член вижда само своето, админът - цялото семейство.
create or replace view public.monthly_totals
with (security_invoker = true) as
select
  user_id,
  category_id,
  date_trunc('month', spent_on)::date as month,
  sum(amount) as total,
  count(*)    as n
from public.expenses
where deleted_at is null
group by user_id, category_id, date_trunc('month', spent_on)::date;

-- ============ ПРАВА ============

-- Анонимните (неавторизирани) заявки не виждат нищо.
revoke all on public.profiles, public.categories, public.expenses,
              public.templates, public.monthly_totals from anon;

grant select, insert, update, delete
  on public.profiles, public.categories, public.expenses, public.templates
  to authenticated;
grant select on public.monthly_totals to authenticated;
grant usage, select on all sequences in schema public to authenticated;

revoke execute on function public.handle_new_user()       from public, anon, authenticated;
revoke execute on function public.is_admin()              from public, anon;
revoke execute on function public.delete_expense(bigint)  from public, anon;
grant  execute on function public.is_admin()              to authenticated;
grant  execute on function public.delete_expense(bigint)  to authenticated;

-- ============ ПО ИЗБОР: НАЧАЛНИ КАТЕГОРИИ ============
-- insert into public.categories (name, sort_order) values
--   ('Храна', 1), ('Храна (навън)', 2), ('Гориво', 3),
--   ('Наем', 4), ('Други', 5), ('Абонаменти', 6);